lesson 8 Recipes App
osmelnyk/rd_homework pull request #2
Opened 2023-10-08 22:22 UTC by osmelnyk

2023-10-09 10:16 UTC, VadymPinchuk requested changes

2023-10-09 10:16 UTC, VadymPinchuk commented on lib/main.dart
> +              ? ListView(
оскільки це складна структура , краще виносити в окремий метод

2023-10-09 10:16 UTC, VadymPinchuk commented on lib/main.dart
> +              : GridView.builder(
і це також

2023-10-09 10:16 UTC, VadymPinchuk commented on lib/main.dart
> +              ? Row(
також

2023-10-09 10:16 UTC, VadymPinchuk commented on lib/main.dart
> +              : Column(
також

2023-10-09 10:16 UTC, VadymPinchuk commented on lib/main.dart
> +            width: MediaQuery.of(context).size.width - 10,
10 - магічна цифра. Яка не має жодного пояснення

2023-10-09 10:16 UTC, VadymPinchuk commented on lib/main.dart
> +class TimeContainer extends StatelessWidget {
чому все в одному файлі Мейн?

2023-10-09 10:16 UTC, VadymPinchuk commented on lib/main.dart
> +class Recipe {
занадто довгий файл мейн

2023-10-09 21:39 UTC, VadymPinchuk approved these changes

2023-10-09 21:39 UTC, VadymPinchuk commented on lib/lesson8/lesson_screen.dart
> +          child: _isListView ? listView() : gridView()),
форматування коду - обовʼязково

2023-10-09 21:39 UTC, VadymPinchuk commented on lib/lesson8/lesson_screen.dart
> +  GridView gridView() {
Widget gridView() - так краще. Більш загальний тип повертати аніж чітко ГрідВью

2023-10-09 21:39 UTC, VadymPinchuk commented on lib/lesson8/lesson_screen.dart
> +      itemBuilder: (context, index) {
якщо контекст тут не використовується. його можна ігнорити наступним чином, замість імені використовуючи **_**

2023-10-09 21:39 UTC, VadymPinchuk commented on lib/lesson8/lesson_screen.dart
> +          onDismissed: (direction) {
те ж саме і про direction

2023-10-09 21:39 UTC, VadymPinchuk commented on lib/lesson8/lesson_screen.dart
> +  ListView listView() {
про тип - те ж саме

2023-10-09 21:39 UTC, VadymPinchuk commented on lib/lesson8/lesson_screen.dart
> +                    width: 8.0,
тут кома не прямо важлива ) оскільки SizedBox(width: 8.0); - фактично однострочна штука

2023-10-09 21:39 UTC, VadymPinchuk commented on lib/lesson8/lesson_screen.dart
> +          child: RecipeCard(recipe: recipe),
не те щоб важливо. але я б його поставив на місце після ключа, оскільки незрозуміло до кого він відноситься

2023-10-10 19:44 UTC, osmelnyk commented on lib/lesson8/lesson_screen.dart
> +          child: RecipeCard(recipe: recipe),
коли переношу догори лінтер свариться:

The 'child' argument should be last in widget constructor invocations.
Try moving the argument to the end of the argument list.

2023-10-10 19:46 UTC, merged